env:
  es6: true
  node: true
extends: airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules: 
  max-len: [2, {"code": 120, "tabWidth": 2, "ignoreUrls": true}]
